<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="width" value = "0.4"/>
<xacro:property name="length" value = "0.6"/>
<xacro:property name="height" value = "0.2"/>
<xacro:property name="wheel_radius" value = "0.1"/>
<xacro:property name="wheel_len" value = "0.05"/>
<xacro:property name = "caster" value = "0.05"/>

    <material name="orange">
        <color rgba="0.6 0.4 0 1"/>
    </material>

    <material name = "gray">
        <color rgba = "0.7 0.7 0.7 1"/>
    </material>

    <material name = "white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name = "black">
        <color rgba = "0 0 0 1"/>
    </material>

    <!-- <link name = "base_footprint"/>

    <joint name = "base_joint" type = "fixed">
        <parent link = "base_footprint"/>
        <child link = "base_link"/>
        <origin xyz = "0 0 0.1" rpy = "0 0 0" />
    </joint> -->

    <link name = "base_link">
        <visual>
            <geometry>
                <box size = "${length} ${width} ${height}" />
            </geometry>
            <origin xyz = "0 0 0.1" rpy = "0 0 0"/>
            <material name= "orange"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${length} ${width} ${height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="5"/>
            <origin xyz="0 0 0" rpy = "0 0 0"/>
            <inertia ixx="0.083" ixy="0" ixz="0" iyy="0.11" iyz="0" izz="0.13"/>
        </inertial>
    </link>

    <link name = "left_wheel">
        <visual>
            <geometry>
                <cylinder radius = "${wheel_radius}" length = "${wheel_len}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "1.57 0 0"/>
            <material name = "gray"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius = "${wheel_radius}" length = "${wheel_len}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "1.57 0 0"/>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <origin xyz="0 0 0" rpy = "0 0 0"/>
            <inertia ixx="0.0014" ixy="0" ixz="0" iyy="0.0014" iyz="0" izz="0.0025"/>
        </inertial>
    </link>
    <joint name = "left_wheel_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "left_wheel"/>
        <origin xyz = "-${length/4} ${width/2 + wheel_len/2} 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <link name = "right_wheel">
        <visual>
            <geometry>
                <cylinder radius = "${wheel_radius}" length = "${wheel_len}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "1.57 0 0"/>
            <material name = "gray"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius = "${wheel_radius}" length = "${wheel_len}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "1.57 0 0"/>
        </collision>
        <inertial>
            <mass value="0.5"/>
            <origin xyz="0 0 0" rpy = "0 0 0"/>
            <inertia ixx="0.0014" ixy="0" ixz="0" iyy="0.0014" iyz="0" izz="0.0025"/>
        </inertial>
    </link>
    <joint name = "right_wheel_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "right_wheel"/>
        <origin xyz = "-${length/4} -${width/2 + wheel_len/2} 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <link name = "caster_wheel">
        <visual>
            <geometry>
                <sphere radius = "${caster}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius = "${caster}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <origin xyz="0 0 0" rpy = "0 0 0"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>
    <joint name = "caster_wheel_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "caster_wheel"/>
        <origin xyz = "0.2 0 -0.05"/>
    </joint>

    <link name = "lidar">
        <visual>
            <geometry>
                <cylinder radius = "0.1" length = "0.05"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius = "0.1" length = "0.05"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </collision>
        <inertial>
            <mass value = "0.1"/>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
        </inertial>
    </link>
    <joint name = "lidar_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "lidar"/>
        <origin xyz = "0 0 0.225" rpy = "0 0 0"/>
    </joint>

    <link name="scan_link" />
    <joint name="scan_joint" type="fixed">
        <parent link="base_link"/>
        <child link="scan_link"/>
        <origin xyz="0.0 0 0.225" rpy="0 0 0"/>
    </joint>

    <link name = "camera">
        <visual>
            <geometry>
                <box size = "0.01 0.025 0.025"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "black"/>
        </visual>
        <collision>
            <geometry>
                <box size = "0.01 0.025 0.025"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </collision>
        <inertial>
            <mass value = "0.01"/>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <inertia ixx="0.000217" ixy = "0" ixz = "0" iyy = "0.000417" iyz = "0" izz = "0.000217"/>
        </inertial>
    </link>
    <joint name = "camera_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "camera"/>
        <origin xyz = "0.305 0 0.2" rpy = "0 0 0"/>
    </joint>

    <gazebo reference="base_link">
        <mu1>1</mu1>
        <mu2>1</mu2>
    </gazebo>

    <gazebo reference="left_wheel">
        <mu1>1</mu1>
        <mu2>1</mu2>
    </gazebo>

    <gazebo reference="right_wheel">
        <mu1>1</mu1>
        <mu2>1</mu2>
    </gazebo>

    <gazebo reference="caster_wheel">
        <mu1>0.000001</mu1>
        <mu2>0.000001</mu2>
    </gazebo>
</robot>